[package]
name = "protongen"
version = "0.17.0"
edition = "2024"
description = "A polished GUI for building Steam / umu-launcher Proton commands on CachyOS"
license = "GPL-3.0-or-later"
default-run = "protongen"

[lib]
name = "protongen_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"

anyhow = "1.0.102"
ehttp = { version = "0.7.1", features = ["json"] }
keyvalues-parser = "0.2.4"
semver = "1.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sevenz-rust2 = "0.22"
sha2 = "0.10"
steamlocate = "2.1.0"
toml = "1.1.2"
